/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCompanySlugRouteImport } from './routes/app/$companySlug'
import { Route as AppCompanySlugIndexRouteImport } from './routes/app/$companySlug/index'
import { Route as ApiCompaniesActiveRouteImport } from './routes/api/companies/active'
import { Route as ApiCompaniesAccessibleRouteImport } from './routes/api/companies/accessible'
import { Route as ApiAuthPathRouteImport } from './routes/api/auth/$path'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCompanySlugMastersIndexRouteImport } from './routes/app/$companySlug/masters/index'
import { Route as AppCompanySlugMastersVoucherTypesRouteImport } from './routes/app/$companySlug/masters/voucher-types'
import { Route as AppCompanySlugMastersUnitsRouteImport } from './routes/app/$companySlug/masters/units'
import { Route as AppCompanySlugMastersPartiesRouteImport } from './routes/app/$companySlug/masters/parties'
import { Route as AppCompanySlugMastersItemsRouteImport } from './routes/app/$companySlug/masters/items'
import { Route as AppCompanySlugMastersAccountsRouteImport } from './routes/app/$companySlug/masters/accounts'
import { Route as AppCompanySlugMastersAccountGroupsRouteImport } from './routes/app/$companySlug/masters/account-groups'
import { Route as ApiCompaniesCompanySlugMastersResourceRouteImport } from './routes/api/companies/$companySlug/masters/$resource'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanySlugRoute = AppCompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanySlugIndexRoute = AppCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanySlugRoute,
} as any)
const ApiCompaniesActiveRoute = ApiCompaniesActiveRouteImport.update({
  id: '/api/companies/active',
  path: '/api/companies/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesAccessibleRoute = ApiCompaniesAccessibleRouteImport.update({
  id: '/api/companies/accessible',
  path: '/api/companies/accessible',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPathRoute = ApiAuthPathRouteImport.update({
  id: '/api/auth/$path',
  path: '/api/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugMastersIndexRoute =
  AppCompanySlugMastersIndexRouteImport.update({
    id: '/masters/',
    path: '/masters/',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const AppCompanySlugMastersVoucherTypesRoute =
  AppCompanySlugMastersVoucherTypesRouteImport.update({
    id: '/masters/voucher-types',
    path: '/masters/voucher-types',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const AppCompanySlugMastersUnitsRoute =
  AppCompanySlugMastersUnitsRouteImport.update({
    id: '/masters/units',
    path: '/masters/units',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const AppCompanySlugMastersPartiesRoute =
  AppCompanySlugMastersPartiesRouteImport.update({
    id: '/masters/parties',
    path: '/masters/parties',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const AppCompanySlugMastersItemsRoute =
  AppCompanySlugMastersItemsRouteImport.update({
    id: '/masters/items',
    path: '/masters/items',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const AppCompanySlugMastersAccountsRoute =
  AppCompanySlugMastersAccountsRouteImport.update({
    id: '/masters/accounts',
    path: '/masters/accounts',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const AppCompanySlugMastersAccountGroupsRoute =
  AppCompanySlugMastersAccountGroupsRouteImport.update({
    id: '/masters/account-groups',
    path: '/masters/account-groups',
    getParentRoute: () => AppCompanySlugRoute,
  } as any)
const ApiCompaniesCompanySlugMastersResourceRoute =
  ApiCompaniesCompanySlugMastersResourceRouteImport.update({
    id: '/api/companies/$companySlug/masters/$resource',
    path: '/api/companies/$companySlug/masters/$resource',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/$companySlug': typeof AppCompanySlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/$path': typeof ApiAuthPathRoute
  '/api/companies/accessible': typeof ApiCompaniesAccessibleRoute
  '/api/companies/active': typeof ApiCompaniesActiveRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/app/$companySlug/masters/account-groups': typeof AppCompanySlugMastersAccountGroupsRoute
  '/app/$companySlug/masters/accounts': typeof AppCompanySlugMastersAccountsRoute
  '/app/$companySlug/masters/items': typeof AppCompanySlugMastersItemsRoute
  '/app/$companySlug/masters/parties': typeof AppCompanySlugMastersPartiesRoute
  '/app/$companySlug/masters/units': typeof AppCompanySlugMastersUnitsRoute
  '/app/$companySlug/masters/voucher-types': typeof AppCompanySlugMastersVoucherTypesRoute
  '/app/$companySlug/masters/': typeof AppCompanySlugMastersIndexRoute
  '/api/companies/$companySlug/masters/$resource': typeof ApiCompaniesCompanySlugMastersResourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/$path': typeof ApiAuthPathRoute
  '/api/companies/accessible': typeof ApiCompaniesAccessibleRoute
  '/api/companies/active': typeof ApiCompaniesActiveRoute
  '/app/$companySlug': typeof AppCompanySlugIndexRoute
  '/app/$companySlug/masters/account-groups': typeof AppCompanySlugMastersAccountGroupsRoute
  '/app/$companySlug/masters/accounts': typeof AppCompanySlugMastersAccountsRoute
  '/app/$companySlug/masters/items': typeof AppCompanySlugMastersItemsRoute
  '/app/$companySlug/masters/parties': typeof AppCompanySlugMastersPartiesRoute
  '/app/$companySlug/masters/units': typeof AppCompanySlugMastersUnitsRoute
  '/app/$companySlug/masters/voucher-types': typeof AppCompanySlugMastersVoucherTypesRoute
  '/app/$companySlug/masters': typeof AppCompanySlugMastersIndexRoute
  '/api/companies/$companySlug/masters/$resource': typeof ApiCompaniesCompanySlugMastersResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/$companySlug': typeof AppCompanySlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/$path': typeof ApiAuthPathRoute
  '/api/companies/accessible': typeof ApiCompaniesAccessibleRoute
  '/api/companies/active': typeof ApiCompaniesActiveRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/app/$companySlug/masters/account-groups': typeof AppCompanySlugMastersAccountGroupsRoute
  '/app/$companySlug/masters/accounts': typeof AppCompanySlugMastersAccountsRoute
  '/app/$companySlug/masters/items': typeof AppCompanySlugMastersItemsRoute
  '/app/$companySlug/masters/parties': typeof AppCompanySlugMastersPartiesRoute
  '/app/$companySlug/masters/units': typeof AppCompanySlugMastersUnitsRoute
  '/app/$companySlug/masters/voucher-types': typeof AppCompanySlugMastersVoucherTypesRoute
  '/app/$companySlug/masters/': typeof AppCompanySlugMastersIndexRoute
  '/api/companies/$companySlug/masters/$resource': typeof ApiCompaniesCompanySlugMastersResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/$companySlug'
    | '/app/'
    | '/api/auth/$'
    | '/api/auth/$path'
    | '/api/companies/accessible'
    | '/api/companies/active'
    | '/app/$companySlug/'
    | '/app/$companySlug/masters/account-groups'
    | '/app/$companySlug/masters/accounts'
    | '/app/$companySlug/masters/items'
    | '/app/$companySlug/masters/parties'
    | '/app/$companySlug/masters/units'
    | '/app/$companySlug/masters/voucher-types'
    | '/app/$companySlug/masters/'
    | '/api/companies/$companySlug/masters/$resource'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app'
    | '/api/auth/$'
    | '/api/auth/$path'
    | '/api/companies/accessible'
    | '/api/companies/active'
    | '/app/$companySlug'
    | '/app/$companySlug/masters/account-groups'
    | '/app/$companySlug/masters/accounts'
    | '/app/$companySlug/masters/items'
    | '/app/$companySlug/masters/parties'
    | '/app/$companySlug/masters/units'
    | '/app/$companySlug/masters/voucher-types'
    | '/app/$companySlug/masters'
    | '/api/companies/$companySlug/masters/$resource'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/$companySlug'
    | '/app/'
    | '/api/auth/$'
    | '/api/auth/$path'
    | '/api/companies/accessible'
    | '/api/companies/active'
    | '/app/$companySlug/'
    | '/app/$companySlug/masters/account-groups'
    | '/app/$companySlug/masters/accounts'
    | '/app/$companySlug/masters/items'
    | '/app/$companySlug/masters/parties'
    | '/app/$companySlug/masters/units'
    | '/app/$companySlug/masters/voucher-types'
    | '/app/$companySlug/masters/'
    | '/api/companies/$companySlug/masters/$resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthPathRoute: typeof ApiAuthPathRoute
  ApiCompaniesAccessibleRoute: typeof ApiCompaniesAccessibleRoute
  ApiCompaniesActiveRoute: typeof ApiCompaniesActiveRoute
  ApiCompaniesCompanySlugMastersResourceRoute: typeof ApiCompaniesCompanySlugMastersResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$companySlug': {
      id: '/app/$companySlug'
      path: '/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AppCompanySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$companySlug/': {
      id: '/app/$companySlug/'
      path: '/'
      fullPath: '/app/$companySlug/'
      preLoaderRoute: typeof AppCompanySlugIndexRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/api/companies/active': {
      id: '/api/companies/active'
      path: '/api/companies/active'
      fullPath: '/api/companies/active'
      preLoaderRoute: typeof ApiCompaniesActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/accessible': {
      id: '/api/companies/accessible'
      path: '/api/companies/accessible'
      fullPath: '/api/companies/accessible'
      preLoaderRoute: typeof ApiCompaniesAccessibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$path': {
      id: '/api/auth/$path'
      path: '/api/auth/$path'
      fullPath: '/api/auth/$path'
      preLoaderRoute: typeof ApiAuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/masters/': {
      id: '/app/$companySlug/masters/'
      path: '/masters'
      fullPath: '/app/$companySlug/masters/'
      preLoaderRoute: typeof AppCompanySlugMastersIndexRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/app/$companySlug/masters/voucher-types': {
      id: '/app/$companySlug/masters/voucher-types'
      path: '/masters/voucher-types'
      fullPath: '/app/$companySlug/masters/voucher-types'
      preLoaderRoute: typeof AppCompanySlugMastersVoucherTypesRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/app/$companySlug/masters/units': {
      id: '/app/$companySlug/masters/units'
      path: '/masters/units'
      fullPath: '/app/$companySlug/masters/units'
      preLoaderRoute: typeof AppCompanySlugMastersUnitsRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/app/$companySlug/masters/parties': {
      id: '/app/$companySlug/masters/parties'
      path: '/masters/parties'
      fullPath: '/app/$companySlug/masters/parties'
      preLoaderRoute: typeof AppCompanySlugMastersPartiesRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/app/$companySlug/masters/items': {
      id: '/app/$companySlug/masters/items'
      path: '/masters/items'
      fullPath: '/app/$companySlug/masters/items'
      preLoaderRoute: typeof AppCompanySlugMastersItemsRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/app/$companySlug/masters/accounts': {
      id: '/app/$companySlug/masters/accounts'
      path: '/masters/accounts'
      fullPath: '/app/$companySlug/masters/accounts'
      preLoaderRoute: typeof AppCompanySlugMastersAccountsRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/app/$companySlug/masters/account-groups': {
      id: '/app/$companySlug/masters/account-groups'
      path: '/masters/account-groups'
      fullPath: '/app/$companySlug/masters/account-groups'
      preLoaderRoute: typeof AppCompanySlugMastersAccountGroupsRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/api/companies/$companySlug/masters/$resource': {
      id: '/api/companies/$companySlug/masters/$resource'
      path: '/api/companies/$companySlug/masters/$resource'
      fullPath: '/api/companies/$companySlug/masters/$resource'
      preLoaderRoute: typeof ApiCompaniesCompanySlugMastersResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCompanySlugRouteChildren {
  AppCompanySlugIndexRoute: typeof AppCompanySlugIndexRoute
  AppCompanySlugMastersAccountGroupsRoute: typeof AppCompanySlugMastersAccountGroupsRoute
  AppCompanySlugMastersAccountsRoute: typeof AppCompanySlugMastersAccountsRoute
  AppCompanySlugMastersItemsRoute: typeof AppCompanySlugMastersItemsRoute
  AppCompanySlugMastersPartiesRoute: typeof AppCompanySlugMastersPartiesRoute
  AppCompanySlugMastersUnitsRoute: typeof AppCompanySlugMastersUnitsRoute
  AppCompanySlugMastersVoucherTypesRoute: typeof AppCompanySlugMastersVoucherTypesRoute
  AppCompanySlugMastersIndexRoute: typeof AppCompanySlugMastersIndexRoute
}

const AppCompanySlugRouteChildren: AppCompanySlugRouteChildren = {
  AppCompanySlugIndexRoute: AppCompanySlugIndexRoute,
  AppCompanySlugMastersAccountGroupsRoute:
    AppCompanySlugMastersAccountGroupsRoute,
  AppCompanySlugMastersAccountsRoute: AppCompanySlugMastersAccountsRoute,
  AppCompanySlugMastersItemsRoute: AppCompanySlugMastersItemsRoute,
  AppCompanySlugMastersPartiesRoute: AppCompanySlugMastersPartiesRoute,
  AppCompanySlugMastersUnitsRoute: AppCompanySlugMastersUnitsRoute,
  AppCompanySlugMastersVoucherTypesRoute:
    AppCompanySlugMastersVoucherTypesRoute,
  AppCompanySlugMastersIndexRoute: AppCompanySlugMastersIndexRoute,
}

const AppCompanySlugRouteWithChildren = AppCompanySlugRoute._addFileChildren(
  AppCompanySlugRouteChildren,
)

interface AppRouteChildren {
  AppCompanySlugRoute: typeof AppCompanySlugRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompanySlugRoute: AppCompanySlugRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthPathRoute: ApiAuthPathRoute,
  ApiCompaniesAccessibleRoute: ApiCompaniesAccessibleRoute,
  ApiCompaniesActiveRoute: ApiCompaniesActiveRoute,
  ApiCompaniesCompanySlugMastersResourceRoute:
    ApiCompaniesCompanySlugMastersResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
