/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCompanySlugRouteImport } from './routes/app/$companySlug'
import { Route as AppCompanySlugIndexRouteImport } from './routes/app/$companySlug/index'
import { Route as ApiCompaniesIndexRouteImport } from './routes/api/companies/index'
import { Route as AppCompanySlugMastersRouteImport } from './routes/app/$companySlug/masters'
import { Route as ApiCompaniesActiveRouteImport } from './routes/api/companies/active'
import { Route as ApiCompaniesAccessibleRouteImport } from './routes/api/companies/accessible'
import { Route as ApiAuthPathRouteImport } from './routes/api/auth/$path'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCompanySlugMastersIndexRouteImport } from './routes/app/$companySlug/masters/index'
import { Route as ApiCompaniesCompanySlugDashboardRouteImport } from './routes/api/companies/$companySlug/dashboard'
import { Route as AppCompanySlugMastersVoucherTypesIndexRouteImport } from './routes/app/$companySlug/masters/voucher-types/index'
import { Route as AppCompanySlugMastersUnitsIndexRouteImport } from './routes/app/$companySlug/masters/units/index'
import { Route as AppCompanySlugMastersPartiesIndexRouteImport } from './routes/app/$companySlug/masters/parties/index'
import { Route as AppCompanySlugMastersItemsIndexRouteImport } from './routes/app/$companySlug/masters/items/index'
import { Route as AppCompanySlugMastersAccountsIndexRouteImport } from './routes/app/$companySlug/masters/accounts/index'
import { Route as AppCompanySlugMastersAccountGroupsIndexRouteImport } from './routes/app/$companySlug/masters/account-groups/index'
import { Route as ApiCompaniesCompanySlugMastersResourceRouteImport } from './routes/api/companies/$companySlug/masters/$resource'
import { Route as ApiCompaniesCompanySlugMastersResourceIdRouteImport } from './routes/api/companies/$companySlug/masters/$resource/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanySlugRoute = AppCompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanySlugIndexRoute = AppCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanySlugRoute,
} as any)
const ApiCompaniesIndexRoute = ApiCompaniesIndexRouteImport.update({
  id: '/api/companies/',
  path: '/api/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugMastersRoute = AppCompanySlugMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppCompanySlugRoute,
} as any)
const ApiCompaniesActiveRoute = ApiCompaniesActiveRouteImport.update({
  id: '/api/companies/active',
  path: '/api/companies/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesAccessibleRoute = ApiCompaniesAccessibleRouteImport.update({
  id: '/api/companies/accessible',
  path: '/api/companies/accessible',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPathRoute = ApiAuthPathRouteImport.update({
  id: '/api/auth/$path',
  path: '/api/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugMastersIndexRoute =
  AppCompanySlugMastersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const ApiCompaniesCompanySlugDashboardRoute =
  ApiCompaniesCompanySlugDashboardRouteImport.update({
    id: '/api/companies/$companySlug/dashboard',
    path: '/api/companies/$companySlug/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCompanySlugMastersVoucherTypesIndexRoute =
  AppCompanySlugMastersVoucherTypesIndexRouteImport.update({
    id: '/voucher-types/',
    path: '/voucher-types/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const AppCompanySlugMastersUnitsIndexRoute =
  AppCompanySlugMastersUnitsIndexRouteImport.update({
    id: '/units/',
    path: '/units/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const AppCompanySlugMastersPartiesIndexRoute =
  AppCompanySlugMastersPartiesIndexRouteImport.update({
    id: '/parties/',
    path: '/parties/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const AppCompanySlugMastersItemsIndexRoute =
  AppCompanySlugMastersItemsIndexRouteImport.update({
    id: '/items/',
    path: '/items/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const AppCompanySlugMastersAccountsIndexRoute =
  AppCompanySlugMastersAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const AppCompanySlugMastersAccountGroupsIndexRoute =
  AppCompanySlugMastersAccountGroupsIndexRouteImport.update({
    id: '/account-groups/',
    path: '/account-groups/',
    getParentRoute: () => AppCompanySlugMastersRoute,
  } as any)
const ApiCompaniesCompanySlugMastersResourceRoute =
  ApiCompaniesCompanySlugMastersResourceRouteImport.update({
    id: '/api/companies/$companySlug/masters/$resource',
    path: '/api/companies/$companySlug/masters/$resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCompaniesCompanySlugMastersResourceIdRoute =
  ApiCompaniesCompanySlugMastersResourceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiCompaniesCompanySlugMastersResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/$companySlug': typeof AppCompanySlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/$path': typeof ApiAuthPathRoute
  '/api/companies/accessible': typeof ApiCompaniesAccessibleRoute
  '/api/companies/active': typeof ApiCompaniesActiveRoute
  '/app/$companySlug/masters': typeof AppCompanySlugMastersRouteWithChildren
  '/api/companies/': typeof ApiCompaniesIndexRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/api/companies/$companySlug/dashboard': typeof ApiCompaniesCompanySlugDashboardRoute
  '/app/$companySlug/masters/': typeof AppCompanySlugMastersIndexRoute
  '/api/companies/$companySlug/masters/$resource': typeof ApiCompaniesCompanySlugMastersResourceRouteWithChildren
  '/app/$companySlug/masters/account-groups/': typeof AppCompanySlugMastersAccountGroupsIndexRoute
  '/app/$companySlug/masters/accounts/': typeof AppCompanySlugMastersAccountsIndexRoute
  '/app/$companySlug/masters/items/': typeof AppCompanySlugMastersItemsIndexRoute
  '/app/$companySlug/masters/parties/': typeof AppCompanySlugMastersPartiesIndexRoute
  '/app/$companySlug/masters/units/': typeof AppCompanySlugMastersUnitsIndexRoute
  '/app/$companySlug/masters/voucher-types/': typeof AppCompanySlugMastersVoucherTypesIndexRoute
  '/api/companies/$companySlug/masters/$resource/$id': typeof ApiCompaniesCompanySlugMastersResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/$path': typeof ApiAuthPathRoute
  '/api/companies/accessible': typeof ApiCompaniesAccessibleRoute
  '/api/companies/active': typeof ApiCompaniesActiveRoute
  '/api/companies': typeof ApiCompaniesIndexRoute
  '/app/$companySlug': typeof AppCompanySlugIndexRoute
  '/api/companies/$companySlug/dashboard': typeof ApiCompaniesCompanySlugDashboardRoute
  '/app/$companySlug/masters': typeof AppCompanySlugMastersIndexRoute
  '/api/companies/$companySlug/masters/$resource': typeof ApiCompaniesCompanySlugMastersResourceRouteWithChildren
  '/app/$companySlug/masters/account-groups': typeof AppCompanySlugMastersAccountGroupsIndexRoute
  '/app/$companySlug/masters/accounts': typeof AppCompanySlugMastersAccountsIndexRoute
  '/app/$companySlug/masters/items': typeof AppCompanySlugMastersItemsIndexRoute
  '/app/$companySlug/masters/parties': typeof AppCompanySlugMastersPartiesIndexRoute
  '/app/$companySlug/masters/units': typeof AppCompanySlugMastersUnitsIndexRoute
  '/app/$companySlug/masters/voucher-types': typeof AppCompanySlugMastersVoucherTypesIndexRoute
  '/api/companies/$companySlug/masters/$resource/$id': typeof ApiCompaniesCompanySlugMastersResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/$companySlug': typeof AppCompanySlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/$path': typeof ApiAuthPathRoute
  '/api/companies/accessible': typeof ApiCompaniesAccessibleRoute
  '/api/companies/active': typeof ApiCompaniesActiveRoute
  '/app/$companySlug/masters': typeof AppCompanySlugMastersRouteWithChildren
  '/api/companies/': typeof ApiCompaniesIndexRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/api/companies/$companySlug/dashboard': typeof ApiCompaniesCompanySlugDashboardRoute
  '/app/$companySlug/masters/': typeof AppCompanySlugMastersIndexRoute
  '/api/companies/$companySlug/masters/$resource': typeof ApiCompaniesCompanySlugMastersResourceRouteWithChildren
  '/app/$companySlug/masters/account-groups/': typeof AppCompanySlugMastersAccountGroupsIndexRoute
  '/app/$companySlug/masters/accounts/': typeof AppCompanySlugMastersAccountsIndexRoute
  '/app/$companySlug/masters/items/': typeof AppCompanySlugMastersItemsIndexRoute
  '/app/$companySlug/masters/parties/': typeof AppCompanySlugMastersPartiesIndexRoute
  '/app/$companySlug/masters/units/': typeof AppCompanySlugMastersUnitsIndexRoute
  '/app/$companySlug/masters/voucher-types/': typeof AppCompanySlugMastersVoucherTypesIndexRoute
  '/api/companies/$companySlug/masters/$resource/$id': typeof ApiCompaniesCompanySlugMastersResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/$companySlug'
    | '/app/'
    | '/api/auth/$'
    | '/api/auth/$path'
    | '/api/companies/accessible'
    | '/api/companies/active'
    | '/app/$companySlug/masters'
    | '/api/companies/'
    | '/app/$companySlug/'
    | '/api/companies/$companySlug/dashboard'
    | '/app/$companySlug/masters/'
    | '/api/companies/$companySlug/masters/$resource'
    | '/app/$companySlug/masters/account-groups/'
    | '/app/$companySlug/masters/accounts/'
    | '/app/$companySlug/masters/items/'
    | '/app/$companySlug/masters/parties/'
    | '/app/$companySlug/masters/units/'
    | '/app/$companySlug/masters/voucher-types/'
    | '/api/companies/$companySlug/masters/$resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app'
    | '/api/auth/$'
    | '/api/auth/$path'
    | '/api/companies/accessible'
    | '/api/companies/active'
    | '/api/companies'
    | '/app/$companySlug'
    | '/api/companies/$companySlug/dashboard'
    | '/app/$companySlug/masters'
    | '/api/companies/$companySlug/masters/$resource'
    | '/app/$companySlug/masters/account-groups'
    | '/app/$companySlug/masters/accounts'
    | '/app/$companySlug/masters/items'
    | '/app/$companySlug/masters/parties'
    | '/app/$companySlug/masters/units'
    | '/app/$companySlug/masters/voucher-types'
    | '/api/companies/$companySlug/masters/$resource/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/$companySlug'
    | '/app/'
    | '/api/auth/$'
    | '/api/auth/$path'
    | '/api/companies/accessible'
    | '/api/companies/active'
    | '/app/$companySlug/masters'
    | '/api/companies/'
    | '/app/$companySlug/'
    | '/api/companies/$companySlug/dashboard'
    | '/app/$companySlug/masters/'
    | '/api/companies/$companySlug/masters/$resource'
    | '/app/$companySlug/masters/account-groups/'
    | '/app/$companySlug/masters/accounts/'
    | '/app/$companySlug/masters/items/'
    | '/app/$companySlug/masters/parties/'
    | '/app/$companySlug/masters/units/'
    | '/app/$companySlug/masters/voucher-types/'
    | '/api/companies/$companySlug/masters/$resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthPathRoute: typeof ApiAuthPathRoute
  ApiCompaniesAccessibleRoute: typeof ApiCompaniesAccessibleRoute
  ApiCompaniesActiveRoute: typeof ApiCompaniesActiveRoute
  ApiCompaniesIndexRoute: typeof ApiCompaniesIndexRoute
  ApiCompaniesCompanySlugDashboardRoute: typeof ApiCompaniesCompanySlugDashboardRoute
  ApiCompaniesCompanySlugMastersResourceRoute: typeof ApiCompaniesCompanySlugMastersResourceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$companySlug': {
      id: '/app/$companySlug'
      path: '/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AppCompanySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$companySlug/': {
      id: '/app/$companySlug/'
      path: '/'
      fullPath: '/app/$companySlug/'
      preLoaderRoute: typeof AppCompanySlugIndexRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/api/companies/': {
      id: '/api/companies/'
      path: '/api/companies'
      fullPath: '/api/companies/'
      preLoaderRoute: typeof ApiCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/masters': {
      id: '/app/$companySlug/masters'
      path: '/masters'
      fullPath: '/app/$companySlug/masters'
      preLoaderRoute: typeof AppCompanySlugMastersRouteImport
      parentRoute: typeof AppCompanySlugRoute
    }
    '/api/companies/active': {
      id: '/api/companies/active'
      path: '/api/companies/active'
      fullPath: '/api/companies/active'
      preLoaderRoute: typeof ApiCompaniesActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/accessible': {
      id: '/api/companies/accessible'
      path: '/api/companies/accessible'
      fullPath: '/api/companies/accessible'
      preLoaderRoute: typeof ApiCompaniesAccessibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$path': {
      id: '/api/auth/$path'
      path: '/api/auth/$path'
      fullPath: '/api/auth/$path'
      preLoaderRoute: typeof ApiAuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/masters/': {
      id: '/app/$companySlug/masters/'
      path: '/'
      fullPath: '/app/$companySlug/masters/'
      preLoaderRoute: typeof AppCompanySlugMastersIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/api/companies/$companySlug/dashboard': {
      id: '/api/companies/$companySlug/dashboard'
      path: '/api/companies/$companySlug/dashboard'
      fullPath: '/api/companies/$companySlug/dashboard'
      preLoaderRoute: typeof ApiCompaniesCompanySlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/masters/voucher-types/': {
      id: '/app/$companySlug/masters/voucher-types/'
      path: '/voucher-types'
      fullPath: '/app/$companySlug/masters/voucher-types/'
      preLoaderRoute: typeof AppCompanySlugMastersVoucherTypesIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/app/$companySlug/masters/units/': {
      id: '/app/$companySlug/masters/units/'
      path: '/units'
      fullPath: '/app/$companySlug/masters/units/'
      preLoaderRoute: typeof AppCompanySlugMastersUnitsIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/app/$companySlug/masters/parties/': {
      id: '/app/$companySlug/masters/parties/'
      path: '/parties'
      fullPath: '/app/$companySlug/masters/parties/'
      preLoaderRoute: typeof AppCompanySlugMastersPartiesIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/app/$companySlug/masters/items/': {
      id: '/app/$companySlug/masters/items/'
      path: '/items'
      fullPath: '/app/$companySlug/masters/items/'
      preLoaderRoute: typeof AppCompanySlugMastersItemsIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/app/$companySlug/masters/accounts/': {
      id: '/app/$companySlug/masters/accounts/'
      path: '/accounts'
      fullPath: '/app/$companySlug/masters/accounts/'
      preLoaderRoute: typeof AppCompanySlugMastersAccountsIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/app/$companySlug/masters/account-groups/': {
      id: '/app/$companySlug/masters/account-groups/'
      path: '/account-groups'
      fullPath: '/app/$companySlug/masters/account-groups/'
      preLoaderRoute: typeof AppCompanySlugMastersAccountGroupsIndexRouteImport
      parentRoute: typeof AppCompanySlugMastersRoute
    }
    '/api/companies/$companySlug/masters/$resource': {
      id: '/api/companies/$companySlug/masters/$resource'
      path: '/api/companies/$companySlug/masters/$resource'
      fullPath: '/api/companies/$companySlug/masters/$resource'
      preLoaderRoute: typeof ApiCompaniesCompanySlugMastersResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/$companySlug/masters/$resource/$id': {
      id: '/api/companies/$companySlug/masters/$resource/$id'
      path: '/$id'
      fullPath: '/api/companies/$companySlug/masters/$resource/$id'
      preLoaderRoute: typeof ApiCompaniesCompanySlugMastersResourceIdRouteImport
      parentRoute: typeof ApiCompaniesCompanySlugMastersResourceRoute
    }
  }
}

interface AppCompanySlugMastersRouteChildren {
  AppCompanySlugMastersIndexRoute: typeof AppCompanySlugMastersIndexRoute
  AppCompanySlugMastersAccountGroupsIndexRoute: typeof AppCompanySlugMastersAccountGroupsIndexRoute
  AppCompanySlugMastersAccountsIndexRoute: typeof AppCompanySlugMastersAccountsIndexRoute
  AppCompanySlugMastersItemsIndexRoute: typeof AppCompanySlugMastersItemsIndexRoute
  AppCompanySlugMastersPartiesIndexRoute: typeof AppCompanySlugMastersPartiesIndexRoute
  AppCompanySlugMastersUnitsIndexRoute: typeof AppCompanySlugMastersUnitsIndexRoute
  AppCompanySlugMastersVoucherTypesIndexRoute: typeof AppCompanySlugMastersVoucherTypesIndexRoute
}

const AppCompanySlugMastersRouteChildren: AppCompanySlugMastersRouteChildren = {
  AppCompanySlugMastersIndexRoute: AppCompanySlugMastersIndexRoute,
  AppCompanySlugMastersAccountGroupsIndexRoute:
    AppCompanySlugMastersAccountGroupsIndexRoute,
  AppCompanySlugMastersAccountsIndexRoute:
    AppCompanySlugMastersAccountsIndexRoute,
  AppCompanySlugMastersItemsIndexRoute: AppCompanySlugMastersItemsIndexRoute,
  AppCompanySlugMastersPartiesIndexRoute:
    AppCompanySlugMastersPartiesIndexRoute,
  AppCompanySlugMastersUnitsIndexRoute: AppCompanySlugMastersUnitsIndexRoute,
  AppCompanySlugMastersVoucherTypesIndexRoute:
    AppCompanySlugMastersVoucherTypesIndexRoute,
}

const AppCompanySlugMastersRouteWithChildren =
  AppCompanySlugMastersRoute._addFileChildren(
    AppCompanySlugMastersRouteChildren,
  )

interface AppCompanySlugRouteChildren {
  AppCompanySlugMastersRoute: typeof AppCompanySlugMastersRouteWithChildren
  AppCompanySlugIndexRoute: typeof AppCompanySlugIndexRoute
}

const AppCompanySlugRouteChildren: AppCompanySlugRouteChildren = {
  AppCompanySlugMastersRoute: AppCompanySlugMastersRouteWithChildren,
  AppCompanySlugIndexRoute: AppCompanySlugIndexRoute,
}

const AppCompanySlugRouteWithChildren = AppCompanySlugRoute._addFileChildren(
  AppCompanySlugRouteChildren,
)

interface AppRouteChildren {
  AppCompanySlugRoute: typeof AppCompanySlugRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompanySlugRoute: AppCompanySlugRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiCompaniesCompanySlugMastersResourceRouteChildren {
  ApiCompaniesCompanySlugMastersResourceIdRoute: typeof ApiCompaniesCompanySlugMastersResourceIdRoute
}

const ApiCompaniesCompanySlugMastersResourceRouteChildren: ApiCompaniesCompanySlugMastersResourceRouteChildren =
  {
    ApiCompaniesCompanySlugMastersResourceIdRoute:
      ApiCompaniesCompanySlugMastersResourceIdRoute,
  }

const ApiCompaniesCompanySlugMastersResourceRouteWithChildren =
  ApiCompaniesCompanySlugMastersResourceRoute._addFileChildren(
    ApiCompaniesCompanySlugMastersResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthPathRoute: ApiAuthPathRoute,
  ApiCompaniesAccessibleRoute: ApiCompaniesAccessibleRoute,
  ApiCompaniesActiveRoute: ApiCompaniesActiveRoute,
  ApiCompaniesIndexRoute: ApiCompaniesIndexRoute,
  ApiCompaniesCompanySlugDashboardRoute: ApiCompaniesCompanySlugDashboardRoute,
  ApiCompaniesCompanySlugMastersResourceRoute:
    ApiCompaniesCompanySlugMastersResourceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
